name: CI

on:
  push:
    branches: [master]
    paths:
      - "build"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [master]
    paths:
      - "build"
      - ".github/workflows/ci.yml"

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install shfmt
        run: |
          wget -qO- "https://github.com/mvdan/sh/releases/download/v3.12.0/shfmt_v3.12.0_linux_amd64" > shfmt
          chmod +x shfmt
          sudo mv shfmt /usr/local/bin/

      - name: Run shfmt
        run: |
          shfmt --diff --indent=2 build

      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: "build"
          check_together: "yes"
          severity: "warning"

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install pandoc
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc texlive-latex-recommended

      - name: Build example.md
        run: ./build example.md
